n = input('Digite algo : ')
print('Classe: {}'.format(type(n)))
print('É decimal : {}'.format(n.isdecimal()))
print('É numérico : {}'.format(n.isnumeric()))
print('É alfabético : {}'.format(n.isalpha()))
print('É alfanumérico : {}'.format(n.isalnum()))
print('É minúsculo : {}'.format(n.islower()))
print('É maiúsculo : {}'.format(n.isupper()))
print('É capitalizada : {}'.format(n.istitle()))
print('É espaço : {}'.format(n.isspace()))
